kind: "PersistentVolumeClaim"
apiVersion: "v1"
metadata:
  name: radarr-data-pvc
  namespace: dnloads  
  annotations:
    volume.alpha.kubernetes.io/storage-class: "longhorn"
  labels:
    app.kubernetes.io/part-of: dnloads
    app.kubernetes.io/name: radarr
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "10Gi"
  storageClassName: longhorn

