kind: "PersistentVolumeClaim"
apiVersion: "v1"
metadata:
  name: nodered-data-pvc
  namespace: hass
  annotations:
    volume.alpha.kubernetes.io/storage-class: "longhorn"
  labels:
    app.kubernetes.io/part-of: hass
    app.kubernetes.io/name: nodered
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "10Gi"
  storageClassName: longhorn