kind: "PersistentVolumeClaim"
apiVersion: "v1"
metadata:
  name: influxdb2-data-pvc
  namespace: database  
  annotations:
    volume.alpha.kubernetes.io/storage-class: "longhorn"
  labels:
    app.kubernetes.io/part-of: database
    app.kubernetes.io/name: influxdb2
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "25Gi"
  storageClassName: longhorn