kind: "PersistentVolumeClaim"
apiVersion: "v1"
metadata:
  name: mariadb-data-pvc
  namespace: database
  annotations:
    volume.alpha.kubernetes.io/storage-class: "longhorn"
  labels:
    app.kubernetes.io/part-of: database
    app.kubernetes.io/name: mariadb
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "60Gi"
  storageClassName: longhorn