kind: "PersistentVolumeClaim"
apiVersion: "v1"
metadata:
  name: keel-data-pvc
  namespace: keel  
  annotations:
    volume.alpha.kubernetes.io/storage-class: "longhorn"
  labels:
    app.kubernetes.io/part-of: keel
    app.kubernetes.io/name: keel
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "10Gi"
  storageClassName: longhorn